// ============================================================================
// ShieldAI — Communication Agent
// Intelligent alert routing, deduplication, escalation, and notification
// management. Correlates alerts from all agents into unified narratives
// and routes them through appropriate channels based on severity.
// ============================================================================

export class CommunicationAgent {
  constructor() {
    this.name = 'Communication';

    /** @type {Map<string, {count: number, lastTick: number, message: object}>} */
    this.dedupMap = new Map();

    /** @type {Map<string, {severity: string, firstTick: number, message: object}>} */
    this.escalationTracker = new Map();

    /** @type {Array<{timestamp: Date, tick: number, routing: object, message: object}>} */
    this.communicationLog = [];

    /** @type {Array<object>} Current tick's messages for zone correlation */
    this.correlationWindow = [];

    /** @type {number} Monotonic tick counter */
    this.tickCounter = 0;

    /** @type {number} Dedup suppression window in ticks */
    this.DEDUP_WINDOW = 5;

    /** @type {number} Max communication log entries */
    this.MAX_LOG_SIZE = 500;

    /**
     * Severity-to-channel mapping for multi-channel simulation.
     * @type {Object<string, string[]>}
     */
    this.channelMap = {
      emergency: ['siren', 'pa_system', 'sms', 'console'],
      critical:  ['pa_system', 'sms', 'console'],
      warning:   ['sms', 'console'],
      info:      ['console'],
    };

    /**
     * Severity-to-recipient mapping for priority-based routing.
     * @type {Object<string, string[]>}
     */
    this.recipientMap = {
      emergency: ['SiteCommander', 'SafetyOfficer', 'AllPersonnel'],
      critical:  ['SafetyOfficer', 'ZoneSupervisor'],
      warning:   ['ZoneSupervisor'],
      info:      ['ControlRoom'],
    };

    /** @type {{warning: number, critical: number}} Escalation SLA in ticks */
    this.escalationSLA = { warning: 20, critical: 10 };

    // ── IEC 62682 / ISA-18.2 Alarm Management ──────────────────────────
    this.alarmMetrics = {
      totalAlarms: 0,
      alarmsPerMinute: [],   // rolling window
      priorityDistribution: { emergency: 0, critical: 0, warning: 0, info: 0 },
      chatteringAlarms: new Map(),  // alarmKey → { count, lastSeen }
      shelvedAlarms: new Map(),     // alarmKey → { reason, expiry }
      staleAlarms: new Map(),       // alarmKey → { firstSeen, tickCount }
      floodActive: false,
      alarmRate: 0,
    };

    // IEC 62682 Priority Matrix: Consequence × Response Time
    this.priorityMatrix = {
      // consequence: { responseTime: priority }
      catastrophic: { immediate: 'emergency', short: 'emergency', medium: 'critical' },
      major:        { immediate: 'emergency', short: 'critical',  medium: 'warning' },
      moderate:     { immediate: 'critical',  short: 'warning',   medium: 'warning' },
      minor:        { immediate: 'warning',   short: 'info',      medium: 'info' },
    };

    /** @type {number} Consecutive ticks below flood threshold */
    this._floodCooldownTicks = 0;
    /** @type {number} Count of flood activation events */
    this._floodEventCount = 0;
  }

  /**
   * Processes all incoming messages from other agents, applies deduplication,
   * correlation, escalation, and priority routing.
   *
   * @param {object[]} allMessages  - All messages generated by other agents this tick.
   * @param {object[]} workers      - Current worker roster.
   * @param {{tick: number, elapsed: number, timestamp: Date}} simulationClock
   * @returns {{ messages: object[], riskFactors: object[] }}
   */
  evaluate(allMessages = [], workers = [], simulationClock = {}) {
    const messages = [];
    const riskFactors = [];
    const now = simulationClock.timestamp || new Date();
    const tick = simulationClock.tick || this.tickCounter;
    this.tickCounter = tick;

    // ── Phase 0: IEC 62682 Alarm Rationalization ──────────────────────
    const rationalized = allMessages.map(msg => this._rationalizeAlarm(msg));
    this.alarmMetrics.totalAlarms += rationalized.length;

    // Chattering detection on rationalized messages
    const chatterFiltered = [];
    for (const msg of rationalized) {
      const alarmKey = `${msg.zone || 'global'}:${msg.severity}:${msg.agent}:${msg.text?.substring(0, 30)}`;
      const chatter = this._detectChattering(alarmKey, tick);
      if (!chatter.chattering) {
        chatterFiltered.push(msg);
      } else if (chatter.count === 4) {
        // Show summary on first suppression
        chatterFiltered.push({
          ...msg,
          text: `🔁 Chattering alarm suppressed (${chatter.count}x in 10 ticks): ${msg.text}`,
          severity: 'info',
        });
      }
    }

    // Flood detection
    const flood = this._detectAlarmFlood(tick, chatterFiltered.length);
    let floodFiltered;
    if (flood.floodActive) {
      floodFiltered = chatterFiltered.filter(
        msg => msg.severity === 'emergency' || msg.severity === 'critical'
      );
      if (flood.suppressed > 0) {
        floodFiltered.push({
          agent: 'Communication',
          severity: 'warning',
          text: `🌊 Alarm flood active: ${flood.suppressed} low-priority alarms suppressed. Only emergency/critical shown.`,
          timestamp: now,
        });
      }
    } else {
      floodFiltered = chatterFiltered;
    }

    // Stale alarm detection
    const staleWarnings = this._detectStaleAlarms(tick, floodFiltered);

    // ── Phase 1: Deduplication ─────────────────────────────────────────
    const deduplicated = this._deduplicateAlerts(floodFiltered, tick);

    // ── Phase 2: Alert Correlation by zone ─────────────────────────────
    const correlated = this._correlateByZone(deduplicated, now);
    const correlatedZoneCount = correlated.length;

    // Merge deduplicated + correlated summary messages
    const enriched = [...deduplicated, ...correlated];

    // ── Phase 3: Escalation check ──────────────────────────────────────
    let escalatedCount = 0;
    for (const msg of enriched) {
      const alertKey = `${msg.zone || 'global'}:${msg.agent}:${msg.text?.substring(0, 40)}`;
      if (msg.severity === 'warning' || msg.severity === 'critical') {
        if (!this.escalationTracker.has(alertKey)) {
          this.escalationTracker.set(alertKey, {
            severity: msg.severity,
            firstTick: tick,
            message: msg,
          });
        }
      }
    }

    // Process escalation SLA breaches
    for (const [key, entry] of this.escalationTracker) {
      const elapsed = tick - entry.firstTick;
      const sla = this.escalationSLA[entry.severity];
      if (sla && elapsed > sla) {
        const newSeverity = entry.severity === 'warning' ? 'critical' : 'emergency';
        escalatedCount++;
        messages.push({
          agent: 'Communication',
          severity: newSeverity,
          text: `⬆️ ESCALATED (${entry.severity}→${newSeverity}): Alert unaddressed for ${elapsed} ticks — "${entry.message.text?.substring(0, 80)}..."`,
          timestamp: now,
          zone: entry.message.zone,
          routing: this._buildRouting(newSeverity),
        });
        // Upgrade tracker entry
        if (newSeverity === 'emergency') {
          this.escalationTracker.delete(key);
        } else {
          entry.severity = newSeverity;
          entry.firstTick = tick;
        }
      }
    }

    // ── Phase 4: Route enriched messages ───────────────────────────────
    for (const msg of enriched) {
      const routing = this._buildRouting(msg.severity);
      const routedMessage = { ...msg, routing };
      messages.push(routedMessage);
      this._logCommunication(routedMessage, tick, now);
    }

    // ── Phase 5: Generate risk factors ─────────────────────────────────
    riskFactors.push({
      sensorId: 'comm-alert-volume',
      value: Math.min(1, allMessages.length / 20),
      weight: 0.3,
    });
    riskFactors.push({
      sensorId: 'comm-escalation-rate',
      value: Math.min(1, escalatedCount / 5),
      weight: 0.5,
    });
    riskFactors.push({
      sensorId: 'comm-correlation-density',
      value: Math.min(1, correlatedZoneCount / 6),
      weight: 0.4,
    });

    // ── Phase 6: Summary message if high volume ────────────────────────
    if (allMessages.length > 10) {
      messages.push({
        agent: 'Communication',
        severity: 'warning',
        text: `📡 Alert storm detected: ${allMessages.length} alerts received this tick. ${deduplicated.length} after deduplication. ${escalatedCount} escalated.`,
        timestamp: now,
        routing: this._buildRouting('warning'),
      });
    }

    // Prune old dedup entries
    this._pruneDedup(tick);

    // Add stale alarm warnings
    for (const sw of staleWarnings) {
      messages.push(sw);
    }

    // Compute IEC 62682 alarm KPIs
    const alarmKPIs = this._computeAlarmKPIs();

    return { messages, riskFactors, alarmKPIs };
  }

  // ── Private: Deduplication ──────────────────────────────────────────────

  /**
   * Groups related alerts by zone+severity and suppresses duplicates within
   * the dedup time window.
   *
   * @param {object[]} incoming - Raw incoming messages.
   * @param {number}   tick    - Current simulation tick.
   * @returns {object[]} Deduplicated messages.
   * @private
   */
  _deduplicateAlerts(incoming, tick) {
    const passed = [];
    for (const msg of incoming) {
      const key = `${msg.zone || 'global'}:${msg.severity}:${msg.agent}`;
      const existing = this.dedupMap.get(key);

      if (existing && (tick - existing.lastTick) < this.DEDUP_WINDOW) {
        // Suppress — increment counter
        existing.count++;
        existing.lastTick = tick;
        existing.message = msg;
      } else {
        // New or window expired — pass through
        const count = existing ? existing.count : 0;
        this.dedupMap.set(key, { count: 1, lastTick: tick, message: msg });
        const enriched = { ...msg };
        if (count > 0) {
          enriched.text = `[${count + 1}x suppressed] ${enriched.text}`;
        }
        passed.push(enriched);
      }
    }
    return passed;
  }

  /**
   * Removes stale entries from the dedup map.
   * @param {number} tick
   * @private
   */
  _pruneDedup(tick) {
    for (const [key, entry] of this.dedupMap) {
      if (tick - entry.lastTick > this.DEDUP_WINDOW * 3) {
        this.dedupMap.delete(key);
      }
    }
  }

  // ── Private: Alert Correlation ──────────────────────────────────────────

  /**
   * Correlates multiple alerts that reference the same zone within a single
   * tick into a unified narrative message.
   *
   * @param {object[]} alerts - Deduplicated alerts for this tick.
   * @param {Date}     now    - Current timestamp.
   * @returns {object[]} Correlated summary messages (one per zone with 2+ alerts).
   * @private
   */
  _correlateByZone(alerts, now) {
    const zoneGroups = new Map();
    for (const alert of alerts) {
      const zone = alert.zone || 'global';
      if (!zoneGroups.has(zone)) zoneGroups.set(zone, []);
      zoneGroups.get(zone).push(alert);
    }

    const correlated = [];
    for (const [zone, group] of zoneGroups) {
      if (group.length < 2) continue;
      const severities = group.map(a => a.severity);
      const highestSeverity = this._highestSeverity(severities);
      const summaries = group.map(a => a.text?.substring(0, 60)).join('; ');
      correlated.push({
        agent: 'Communication',
        severity: highestSeverity,
        text: `🔗 Zone ${zone}: ${group.length} concurrent alerts — ${summaries}`,
        timestamp: now,
        zone,
      });
    }
    return correlated;
  }

  /**
   * Returns the highest severity from an array of severity strings.
   * @param {string[]} severities
   * @returns {string}
   * @private
   */
  _highestSeverity(severities) {
    const order = { emergency: 4, critical: 3, warning: 2, info: 1 };
    let max = 'info';
    for (const s of severities) {
      if ((order[s] || 0) > (order[max] || 0)) max = s;
    }
    return max;
  }

  // ── Private: Routing ────────────────────────────────────────────────────

  /**
   * Builds a routing descriptor for a given severity level.
   *
   * @param {string} severity - Alert severity.
   * @returns {{ channels: string[], recipients: string[] }}
   * @private
   */
  _buildRouting(severity) {
    return {
      channels: this.channelMap[severity] || ['console'],
      recipients: this.recipientMap[severity] || ['ControlRoom'],
    };
  }

  // ── Private: Communication Log ──────────────────────────────────────────

  /**
   * Appends a routed message to the audit-ready communication log.
   *
   * @param {object} message - The routed message.
   * @param {number} tick    - Current tick.
   * @param {Date}   now     - Current timestamp.
   * @private
   */
  _logCommunication(message, tick, now) {
    this.communicationLog.push({
      timestamp: now,
      tick,
      routing: message.routing,
      message: { agent: message.agent, severity: message.severity, text: message.text, zone: message.zone },
    });
    // Cap log size
    if (this.communicationLog.length > this.MAX_LOG_SIZE) {
      this.communicationLog = this.communicationLog.slice(-this.MAX_LOG_SIZE);
    }
  }

  // ── IEC 62682 Alarm Management Methods ───────────────────────────────────

  /**
   * Apply IEC 62682 priority matrix to rationalize alarm priority.
   * Maps message severity to consequence level and estimates response time.
   *
   * @param {object} message - Incoming alarm message.
   * @returns {object} Rationalized message with adjusted priority.
   * @private
   */
  _rationalizeAlarm(message) {
    // Map severity to consequence level
    const severityToConsequence = {
      emergency: 'catastrophic',
      critical: 'major',
      warning: 'moderate',
      info: 'minor',
    };
    const consequence = severityToConsequence[message.severity] || 'minor';

    // Estimate response time based on zone and type
    let responseTime = 'medium'; // default
    if (message.zone && (message.text?.includes('gas') || message.text?.includes('H2S') || message.text?.includes('CH4'))) {
      responseTime = 'immediate';
    } else if (message.severity === 'emergency' || message.severity === 'critical') {
      responseTime = 'short';
    }

    // Look up rationalized priority from IEC 62682 matrix
    const matrixRow = this.priorityMatrix[consequence];
    const rationalizedPriority = matrixRow ? (matrixRow[responseTime] || message.severity) : message.severity;

    // Track priority distribution
    if (this.alarmMetrics.priorityDistribution[rationalizedPriority] !== undefined) {
      this.alarmMetrics.priorityDistribution[rationalizedPriority]++;
    }

    return {
      ...message,
      severity: rationalizedPriority,
      _originalSeverity: message.severity,
      _rationalized: true,
      _consequence: consequence,
      _responseTime: responseTime,
    };
  }

  /**
   * Detect chattering alarms — same alarm firing >3 times in 10 ticks.
   *
   * @param {string} alarmKey - Unique alarm identifier.
   * @param {number} tick     - Current simulation tick.
   * @returns {{ chattering: boolean, count: number }}
   * @private
   */
  _detectChattering(alarmKey, tick) {
    const entry = this.alarmMetrics.chatteringAlarms.get(alarmKey);

    if (entry && (tick - entry.lastSeen) <= 10) {
      entry.count++;
      entry.lastSeen = tick;
      if (entry.count > 3) {
        return { chattering: true, count: entry.count };
      }
      return { chattering: false, count: entry.count };
    }

    // New or expired alarm
    this.alarmMetrics.chatteringAlarms.set(alarmKey, { count: 1, lastSeen: tick });
    return { chattering: false, count: 1 };
  }

  /**
   * Detect alarm floods — >10 alarms in current tick triggers flood mode.
   * Auto-deactivates when rate drops below 5/tick for 3 consecutive ticks.
   *
   * @param {number} tick       - Current simulation tick.
   * @param {number} alarmCount - Number of alarms in current tick.
   * @returns {{ floodActive: boolean, suppressed: number }}
   * @private
   */
  _detectAlarmFlood(tick, alarmCount) {
    this.alarmMetrics.alarmsPerMinute.push(alarmCount);
    if (this.alarmMetrics.alarmsPerMinute.length > 60) {
      this.alarmMetrics.alarmsPerMinute.shift();
    }

    if (alarmCount > 10) {
      if (!this.alarmMetrics.floodActive) {
        this._floodEventCount++;
      }
      this.alarmMetrics.floodActive = true;
      this._floodCooldownTicks = 0;
      const suppressed = alarmCount - Math.floor(alarmCount * 0.3); // estimate
      return { floodActive: true, suppressed };
    }

    if (this.alarmMetrics.floodActive) {
      if (alarmCount < 5) {
        this._floodCooldownTicks++;
        if (this._floodCooldownTicks >= 3) {
          this.alarmMetrics.floodActive = false;
          this._floodCooldownTicks = 0;
        }
      } else {
        this._floodCooldownTicks = 0;
      }
    }

    return { floodActive: this.alarmMetrics.floodActive, suppressed: 0 };
  }

  /**
   * Detect stale alarms — same alarm active for >30 ticks without state change.
   *
   * @param {number}   tick     - Current simulation tick.
   * @param {object[]} messages - Current tick's messages.
   * @returns {object[]} Stale alarm warning messages.
   * @private
   */
  _detectStaleAlarms(tick, messages) {
    const warnings = [];
    const currentKeys = new Set();

    for (const msg of messages) {
      const key = `${msg.zone || 'global'}:${msg.agent}:${msg.severity}`;
      currentKeys.add(key);

      if (!this.alarmMetrics.staleAlarms.has(key)) {
        this.alarmMetrics.staleAlarms.set(key, { firstSeen: tick, tickCount: 0 });
      }
      const entry = this.alarmMetrics.staleAlarms.get(key);
      entry.tickCount++;

      const activeDuration = tick - entry.firstSeen;
      if (activeDuration > 30) {
        warnings.push({
          agent: 'Communication',
          severity: 'warning',
          text: `⏰ Stale alarm: ${msg.agent} in ${msg.zone || 'global'} active for ${activeDuration} ticks — investigate or shelve`,
          timestamp: new Date(),
          zone: msg.zone,
        });
      }
    }

    // Remove entries no longer present
    for (const [key] of this.alarmMetrics.staleAlarms) {
      if (!currentKeys.has(key)) {
        this.alarmMetrics.staleAlarms.delete(key);
      }
    }

    return warnings;
  }

  /**
   * Generate IEC 62682 / ISA-18.2 alarm management KPIs.
   *
   * @returns {object} Alarm management KPIs.
   * @private
   */
  _computeAlarmKPIs() {
    const recent = this.alarmMetrics.alarmsPerMinute;
    const alarmRate = recent.length > 0
      ? recent.reduce((s, v) => s + v, 0) / recent.length
      : 0;

    // Count chattering alarms
    let chatteringCount = 0;
    for (const [, entry] of this.alarmMetrics.chatteringAlarms) {
      if (entry.count > 3) chatteringCount++;
    }
    const totalTracked = this.alarmMetrics.chatteringAlarms.size || 1;
    const chatteringPct = (chatteringCount / totalTracked) * 100;

    // Priority distribution percentages
    const dist = this.alarmMetrics.priorityDistribution;
    const totalPriority = dist.emergency + dist.critical + dist.warning + dist.info || 1;
    const priorityDistribution = {
      emergency: Math.round((dist.emergency / totalPriority) * 100),
      critical: Math.round((dist.critical / totalPriority) * 100),
      warning: Math.round((dist.warning / totalPriority) * 100),
      info: Math.round((dist.info / totalPriority) * 100),
    };

    return {
      alarmRate: Math.round(alarmRate * 100) / 100,
      chatteringPct: Math.round(chatteringPct * 100) / 100,
      priorityDistribution,
      floodEvents: this._floodEventCount,
      staleCount: this.alarmMetrics.staleAlarms.size,
      ISA18_2_compliant: alarmRate < 6,
      targetRate: 6,  // ISA-18.2 target: ~6 alarms per hour
    };
  }

  /**
   * Resets all communication agent state to initial values.
   */
  reset() {
    this.dedupMap.clear();
    this.escalationTracker.clear();
    this.communicationLog = [];
    this.correlationWindow = [];
    this.tickCounter = 0;
    // Reset IEC 62682 state
    this.alarmMetrics = {
      totalAlarms: 0,
      alarmsPerMinute: [],
      priorityDistribution: { emergency: 0, critical: 0, warning: 0, info: 0 },
      chatteringAlarms: new Map(),
      shelvedAlarms: new Map(),
      staleAlarms: new Map(),
      floodActive: false,
      alarmRate: 0,
    };
    this._floodCooldownTicks = 0;
    this._floodEventCount = 0;
  }
}
